### PR TITLE
Website update

### PR DESCRIPTION
**Pull request by Andy-ABTec**
Hi @MarkSummerville, hopefully this will be pretty much "it" until you guys start adding/changing stuff!

I think index is a little more "interesting" now and the navigation is a little more logical (within the confines of the template)...

Please take a look before merging: -

https://andy-abtec.github.io/tvrename/

Let me know what you think.

### CODE REVIEW

**Comment by JoeBiellik** [comment]
Looks good to me

**Comment by Andy-ABTec** [comment]
Fixed the download link in the main part of the page to point to the latest exe.

Hadn't realized Jekyll was generating its own id tags from headings, so ended up with two items with the same id on the index page (oops!).

Now the penny has dropped all the references to download are fixed...

**Comment by MarkSummerville** [comment]
I feel that you are managing to create a site DESPITE the leap day theme rather than because of it! It feels a little limited now you have produced so much content.

So, just to see what it looks like I'm having a play with a new theme: https://mmistakes.github.io/minimal-mistakes/about/ on https://github.com/TV-Rename/Website. 
I can imagine us having DOWNLOAD / SUPPORT / MANUAL as the three items across the top which wold allow the detail to be under LHS navigational menus. I have not quite got it working yet though and am just about to go away for a week or so. If you'd like then feel free to have a play / hack around and let me know if you manage to fix it!

**Comment by MarkSummerville** [comment]
PS  I have no intention of suggesting a move yet - just seeing what a more fully featured theme can do for us

**Comment by Andy-ABTec** [comment]
@MarkSummerville, That's cool, I'll have a play and see how I get on... Though having said that; now the page organisation is a bit better I think it's a fairly good fit in Leap Day, I can still free up one menu button by losing the direct link to the forum if necessary. As it stands I'm envisioning things growing vertically rather than horizontally.

I'm assuming as you like what I've done with the place, otherwise it wouldn't have been merged.

**Comment by Andy-ABTec** [comment]
Sorry, have you dumped any of our content into the theme? It looks like I can see familiar files but I can't find my way into a live site?

**Comment by MarkSummerville** [comment]
HI,

I have had a play about and have it (approximately) working. Still much to do, but enough to take a look to decide if a more active/complete theme would help us now we have more content.

https://tv-rename.github.io/Website/manual/quickstart/ is the web version

https://github.com/TV-Rename/Website is the repository

Take a look - have a play and let me know your thoughts.

Cheers

Mark

**Comment by MarkSummerville** [comment]
Just done some more updates - Not quite there yet, but have a homepage and a few other pages added in. If people are interested I can send a little more time getting it up and running when I'm back. @Andy-ABTec, @JoeBiellik, @mhurwood  - let me know what you think

Cheers

**Comment by JoeBiellik** [comment]
@MarkSummerville This looks good, but I don't think its safe to have the repo as a fork of the theme. I do prefer this new theme, just because it takes better advantage of a widescreen, but I defer to @Andy-ABTec as to what he wants to use as the docs main maintainer.

**Comment by Andy-ABTec** [comment]
&lt;rant&gt;
Bit of a shame you didn't "prefer" a different theme a month and a half ago really...
Its a bit like me saying hey I don't like the .NET framework, do it in something else!
&lt;/rant&gt;

It makes much better use of the real estate but I think it looks bland and the menus make it "bitty" - navigation will be interesting to say the least.

Most of the custom css will need reworking and all the graphics will need re-creating as they were scaled down to by 20-25% to fit the smaller viewport. and the look like crap now.

How does the quickstart page look in TV Rename?

**Comment by MarkSummerville** [comment]
Hi @Andy-ABTec, I understand your frustration. I am very grateful of the work you've put into the website. It would not look anywhere near as complete or helpful without your efforts. The ability to use custom templates for  `gh-page`  is a new thing. When I decided to move the website into GitHub from sitting on Steve's machine there were only the choice of the 13 stock standard ones - this was not an option. Even if it was then given we only had 2-3 pages it was probably fit for purpose. Now that you have added a great deal to the site so that we've a lot more good quality, up to date content and it 'feels' that we have outgrown it. As I said above we have a good looking website despite the theme, rather than because of it! Further 'Leap Day' is not having updates as fast as we'd like. As discussed [here](https://github.com/TV-Rename/tvrename/issues/280#issuecomment-356804404).

Both @JoeBiellik and I have said that as the owner of the website, it's really up to you about whether the effort/reward of moving to a new template is worth it. We can only comment on whether we like/dislike the new theme. Neither @JoeBiellik nor I really know how much work it is to get the site looking good in Leap Day or how much work it would be in a new theme. I know the theory (of the 13 themes at least) was that they should be interchangeable, or at least a [cut & paste](https://github.com/TV-Rename/tvrename/issues/280#issuecomment-356857335), but I suspect we have long seemed to have moved past that.

It's down to you to decide whether the switch is worth it. I chose to trial it because it has more non-blog features:
 * Improved Navigation [LHS](https://tv-rename.github.io/Website/manual/userguide/)
 * Better Fullscreen pages [dodgy image, but idea is here](https://tv-rename.github.io/Website/)
 * Ongoing Support [here](https://github.com/mmistakes/minimal-mistakes/commits/master)
 * [Gallery ](https://mmistakes.github.io/minimal-mistakes/post%20formats/post-gallery/)
 * Is responsive

But as I said it's up to you. I'd me more than happy with the current theme. I just worry that we'll be banging our head against a brick wall with it.

**Comment by MarkSummerville** [comment]
Hi @JoeBiellik I initially tried a clean install, but ended up following these setup (instructions)[https://mmistakes.github.io/minimal-mistakes/docs/installation/] which advised forking the repository and using [this method](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/#use-git) to update as the upstream 'template' is updated.

Having said that, I'm happy to go in either direction - just wanted to point out why I set it up the way it is. Your knowledge and instinct on these things is far better than mine.

**Comment by Andy-ABTec** [comment]
I think for now we leave things as they are, @JoeBiellik's work on the jQuery stuff has been a big help and things are pretty much where I envisioned them, tweaking and other small updates are easy because I know my way around.

I will however take a good look at the new suggested template, but before I try and do much more with it I need to get a totally local version running (as I did with the old site). Trying to test stuff on a system that is a PITA to edit and takes a few minutes to respond to changes is not helpful to say the least.

**Comment by Andy-ABTec** [comment]
Well that'll be minimal-mistakes running on my laptop then, just need some content...

**Pull request merged**
