### PR TITLE
Added file size to JSON download source

### PR DESCRIPTION
**Pull request by MarkSummerville**
Please describe all changes; make changes atomic and link changes back to the bug, feature request or issue that they address

### CODE REVIEW

**Comment by MarkSummerville** [comment]
Closing as functionality added via https://github.com/TV-Rename/tvrename/commit/8dfaf1a1d07c8999878ff90e187abeb4ce7b61f9

Including setting via preferences and existing GB.MB function

**Comment by Andy-ABTec** [comment]
Please can you elaborate "setting via preferences"

Ta!

**Comment by MarkSummerville** [comment]
Added a new field on the JSON finder page to pull file size too

**Comment by Andy-ABTec** [comment]
Thanks, I took it as a change in Preferences>RSS/JSON Search" but it looks like  something I needn't worry about...

**Comment by MarkSummerville** [comment]
There are some other new settings on the search tab to only search json and rss when the scan is manually initiated

I’ve just added another setting for the new ‘ignore previously seen’ episodes

**Comment by Andy-ABTec** [comment]
OK, I'll go through the Search tab and update...

**Pull request closed without merging**
