### PR TITLE
Resharper auto updates

### PR DESCRIPTION
**Pull request by MarkSummerville**
For review

### CODE REVIEW

**Comment by JoeBiellik** [comment]
I attempted this myself a few days ago but found that due to the number of changes merging would cause issues for everyone working on the project. Now we have fewer branches its much more feasible, but if we are going to do a big merge it needs to be done soon before too many others make their own changes.

I now think it may be better to make formatting changes only on files you are modifying for other reasons, it will take longer to fix all the formatting, but it also gives us a chance to review each file.

**Comment by MarkSummerville** [comment]
Yeah -good point. I mean to adda  comment to indicate that I never intended to actually merge this into mster - more this was an opportunity to look at what would happen and agree we are happy with the proposed changes

**Comment by JoeBiellik** [comment]
In reply to @MarkSummerville:
>I don't like the _Var syntax for private member variable - looks clumsy to me

I really don't like using any kind of member prefix; underscore, "m" or otherwise. I would always just use a single descriptive ``camelCase`` word.

>I like consts being in all caps (eg MyListView)

Do you mean you like types (MyListView) to be ``PascalCase``? When you say consts I think of ``private const int MY_CONST = 1`` which can be put in ``UPPER_CASE``.

I happy with Resharper's defaults 99% of the time, it does a great job of following official and community standards. The [MS docs](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) are actually very detailed and include some examples as well.

**Comment by MarkSummerville** [comment]
Yeah. I was talking about CONST variables which I have a personal preference to be in ALL-CAPS. I’ll take a look at the next guidelines - might bring me up to date!

**Comment by MarkSummerville** [comment]
Ps glad we agree on prefixes!

**Comment by MarkSummerville** [comment]
Closing as this was just for info anyway

**Pull request closed without merging**
