### PR TITLE
Application Update Control 

### PR DESCRIPTION
**Pull request by hummigbird1**
This feature gives the user a greater control about the "Application Update Check"-
It allows:
- Disabling checking for updates entirely
- Checking for Updates in predefined intervals (daily, every 12 hours, etc.)
- Disabling the "Update available" popup on start (while still indicating available updates via the toolbar indication)

### CODE REVIEW

**Comment by hummigbird1** [comment]
I am unable to see the details of the "Better Code Hub" check failure.

**Comment by SirSparkles** [comment]
Thank you so much for taking the time to contribute changes, it's really appreciated. Code looks great. I'm still working through issues with Movies and the new TMDB libraries so any changes you have feel free to contribute

thanks again

**Comment by SirSparkles** [comment]
Why have the config settings in another file? I think we should merge them into the main settings file

**Comment by SirSparkles** [comment]
Also - would be nice to finesse the UI layout for the new configuration settings. But love the options and functionality

**Comment by hummigbird1** [comment]
> 
> 
> Why have the config settings in another file? I think we should merge them into the main settings file
Are you talking about the "State.xml"? 
If so, they are not settings. That is why I put them in a separate file.

**Comment by hummigbird1** [comment]
> 
> 
> Thank you so much for taking the time to contribute changes, it's really appreciated. Code looks great. I'm still working through issues with Movies and the new TMDB libraries so any changes you have feel free to contribute
> 
> thanks again

Thank you for accepting my PR! 
I am happy it was accepted.

**Comment by Chlorel** [comment]
Having the settings in a separate file can be interesting when you want to create a new database and not have to find all the small options found as you use the program. An alternative could be to be able to export and then import the settings into the new database.

**Pull request merged**
