### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by MarkSummerville**
Main Change:
 * #276 - Notification of new version being available

Enhancements:
 * #10 - Improved 'keep together' functionality
 * #240 - Make % dirty configurable
 * #241 - Make 'season' as a word configurable and other search terms that mean 'season'
 * #277  - Added 'beta' mode that allows part working functions to be showcased

Bug Fixes:
 * #273 - Fix exporter bug that caused crash if path was missing 
 * #285 - Fix to the banners to calculate the best banner rather than rely on the TVDB to get it right
 * #286 - Fix bug that meant that the 'Find Unused Files' failed when doing a full scan

Added ShowSummary, DuplicateFinder (in alpha) behind the new Beta tag

I will put together a release for this as I want to test the scenario that there is a more recent 'pre-release' version in the json file. I need to have this to test @Andy-ABTec javascript in the website and the parsing in the update-notification code.

Please can you still review as I'll put another change in tonight with the changes to the Auto-Update code

### CODE REVIEW

**Comment by JoeBiellik** [comment]
I'll give the RC a go tomorrow, but the code looks good.

I still think we could do better than just checking ``!=`` when comparing version numbers even if its just some basic regex like ``(\d+)\.(\d+)\.(\d+)(-\w+)?(\.\d+)?``.

**Comment by MarkSummerville** [comment]
Yeah - will do something a little better. I am yet to code the 'follow beta versions' path - wanted an RC in play so I could test it out properly.

However either the versions are the same (no problem) or the versions are different. If they are different then the local version cannot be newer than the 'latest' from the server, so be must be older (hence need an update). So even if I know how old the release is by comparing the versions in detail, I'm not sure what I'd do with the extra information.

**Comment by JoeBiellik** [comment]
Does GH's API return the newest chronologically or the highest version number? My concern is we release 3.0 then 2.4 prompting a downgrade.

**Comment by MarkSummerville** [comment]
I'm not sure that we'd do that, but I can code it up just to be sure. If I don't we'll definitely end up doing it that way!

**Pull request merged**
