### PR TITLE
Style Guidelines

### PR DESCRIPTION
**Pull request by JoeBiellik**
Update Resharper code style guidelines

### CODE REVIEW

**Comment by MarkSummerville** [comment]
I'm just playing with ReSharper and wanted to propose the following additions:

```
	<s:String x:Key="/Default/CodeStyle/CSharpVarKeywordUsage/ForBuiltInTypes/@EntryValue">UseExplicitType</s:String>
	<s:String x:Key="/Default/CodeStyle/CSharpVarKeywordUsage/ForOtherTypes/@EntryValue">UseExplicitType</s:String>
	<s:String x:Key="/Default/CodeStyle/CSharpVarKeywordUsage/ForSimpleTypes/@EntryValue">UseExplicitType</s:String>
	<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/Abbreviations/=JPG/@EntryIndexedValue">JPG</s:String>
	<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/Abbreviations/=XML/@EntryIndexedValue">XML</s:String>
```
Thoughts?

**Comment by JoeBiellik** [comment]
The naming conventions are fine, I think we just ignore them all for now, but eventually I would like us to use standard conventions (``Xml`` etc).

I don't personally like using explict types, I prefer the C# 3.0 ``var`` keyword just for brevity:
``Dictionary<string, string> dict  = new Dictionary<string, string>();`` vs
``var dict  = new Dictionary<string, string>();``

I find that almost everyone uses IDE's with type hinting so you can always just hover over the variable to see the type, but if you want to enforce full types I don't mind.

**Comment by MarkSummerville** [comment]
I would have thought `XML` would be the standard, but happy to go either way on this.

I prefer explicit types, as I find it easier to read and easier to pickup if I am new to the code. Maybe I'm just used to older IDEs where it was essential to having a useful tooltip.

**Comment by JoeBiellik** [comment]
From the Microsoft capitalization conventions documentation:
> Do capitalize only the first character of acronyms with three or more characters, except the first word of a camel-cased identifier.

It's [System.Xml](https://msdn.microsoft.com/en-us/library/gg145036(v=vs.110).aspx) for example, but System.IO and Microsoft.VisualBasic.

**Pull request merged**
