### PR TITLE
Cleanup auto folder monitor

### PR DESCRIPTION
**Pull request by JoeBiellik**
This cleans up and documents the auto folder monitor, no logic or breaking changes.

### CODE REVIEW

**Comment by MarkSummerville** [comment]
@JoeBiellik thanks for this. However before we merge in the clean-ups and refactors I'm keen to get a 2.3 FINAL out. Then we can rejig the code ready for a v2.4 or v3 release. ATM I'm thinking that the v2.4 would be our refactor and cleanup release, with v3 being the new UI release (ie we save the major version for the changes that will make a big difference to users). But happy either way if there is a good reason for it. From the forums it feels like v2.4 is fairly bug free at the moment and we only risk adding bugs (such as the div 0 I introduced). Sound OK?

**Comment by JoeBiellik** [comment]
How close are we to a release? Still not sure what is left on the table for 2.3.

The plan with this and other recent commits was just to clean up the existing code so that when it came to refactor we had some basic comments and we aren't dealing with unorganised and unused code. The abstractions and changes I've made where the best I could do without breaking logic or more serious changes and are mostly R# recommendations, however you are right, its possible bugs may slip through.

If these changes won't make it into the next release then I'll close them and focus on a full breaking refactor for the next major version. I personally think its a bad idea to invest in changing the UI/adding more features until the codebase has been properly reviewed, as we are just adding more technical debt.

**Comment by MarkSummerville** [comment]
Nothing left - just putting out a final RC now. Just wanted to give it time on the forums for people to use it and report any issues. I'll get it out and then we can be clear to move forward without time pressure and the risk of breaking stuff. I'm keen to get this out into user land as I'm aware the last official release was best part of a decade ago!

**Comment by MarkSummerville** [comment]
If you're able to double-check https://github.com/TV-Rename/tvrename/releases/tag/2.3.9 then I can mark it as the final version and then we are clear. Sorry, but without a PC ATM, I'm a bit hamstrung.

**Comment by JoeBiellik** [comment]
Release works great, however as you created it with a tag of ``2.3.9`` that is the version the installer and application display. Obviously you can use a tag of ``2.3.0`` for the final release, but for this RC I'm worried the version number may be misleading to users. AppVeyor is set up so a tag of ``2.3.0-rc4`` should work and display the version correctly.

**Comment by MarkSummerville** [comment]
OK - sorry for messing up the hard work you've done on the version numbers.

Why don't we skip 2.3 then and move to 2.4!

Do I need to update:

```
[assembly: AssemblyVersion("2.3.0.0")]
[assembly: AssemblyFileVersion("2.3.0")]
[assembly: AssemblyInformationalVersion("2.3 RC")] // Display version

```
to 2.4.xx then create the release as 2.4.0

Does that sound about right?

**Comment by JoeBiellik** [comment]
I'm not sure skipping an entire version is a good idea. I can remove the ``2.3.9`` tag and recreate it correctly if you would like?

The assembly version numbers will be replaced by AppVeyor, they are only seen when doing local builds.

**Comment by MarkSummerville** [comment]
Wouldn't we have to remove all `2.3.x` tags?

**Comment by JoeBiellik** [comment]
We could simply rename all the ``2.3.x`` to the correct ``2.3.0-rcX`` tags, I think that helps anyone who comes across them in the future.

**Comment by MarkSummerville** [comment]
OK - that'd be great

**Comment by JoeBiellik** [comment]
So I've cloned all the ``2.3.x`` tags to ``rc1-4``. I had to recreate the GitHub releases, so the timestamps on those are off, but the times on the tags and commits are as normal. Please check them over and I will then remove the old releases and tags.

AppVeyor kicked off again and rebuilt the exe's as I published the tags, so should be done on that front. ``TVRename-2.3.0-rc4.exe`` installs and displays ``2.3 RC 4`` correctly.

**Comment by JoeBiellik** [comment]
Just as a note, both RC1 and RC2 were created from the same commit and are identical, it was like this before I renamed it.

**Comment by MarkSummerville** [comment]
Thank you so much @JoeBiellik . I have pushed a new release. v2.3 is officially out now!

**Comment by MarkSummerville** [comment]
Chuffed that's out! I'm not sure whether the best practice is to merge these to master and create a branch from the 2.3 tag if we have to put out an emergency fix or whether to merge these changes onto a 'v3 ' branch and then merge all v3 changes to master once we are ready (or close to). I'll defer to @JoeBiellik  and @mhurwood on these matters

**Pull request merged**
